spring:
  profiles:
    active: local
---
spring:
  profile: local
  datasource:
    url: jdbc:h2:mem:diary
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db/diary
  jpa: 
    generate-ddl: true
    show-sql: true
    hibernate: 
      ddl-auto: create
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl